locationlib/urls.py
from django.conf.urls import patterns, url

from locationlib import views

urlpatterns = patterns('',
	url(r'^$', views.index, name='index'),
	url(r'^new/$', views.new, name='new'),
	url(r'^savenew/$', views.savenew, name='savenew'),
	url(r'^(?P<location_id>\d+)/$', views.detail, name='detail'),
	url(r'^(?P<location_id>\d+)/edit/$', views.edit, name='edit'),
	url(r'^(?P<location_id>\d+)/save/$', views.save, name='save'),
	url(r'^(?P<location_id>\d+)/delete/$', views.delete, name='delete'),
	)

pushpin/urls.py
from django.conf.urls import patterns,include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'pushpin.views.home', name='home'),
    url(r'^signup/$', 'pushpin.views.signup', name="signup"),
    url(r'^login/$', 'pushpin.views.userLogin', name="userLogin"),
    url(r'^newuser/$', 'pushpin.views.createUser', name='createUser'),
    url(r'^authenticator/$', 'pushpin.views.authenticator', name='authenticator'),
    url(r'^logout/$', 'pushpin.views.userLogout', name='logout'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^locationlib/', include('locationlib.urls', namespace="locationlib")),
    url(r'^users/', include('users.urls', namespace='users')),
    )

users/urls.py
from django.conf.urls import patterns, url

from users import views

urlpatterns = patterns('',
	url(r'^(?P<user_id>\d+)/$' , views.profile, name='profile'),
	url(r'^(?P<user_id>\d+)/edit/$', views.edit, name='edit'),
	url(r'^(?P<user_id>\d+)/save/$', views.save, name='save'),
	url(r'^(?P<user_id>\d+)/places/$', views.places_index, name='places'),
	url(r'^(?P<user_id>\d+)/add/$', views.add, name='add'),
	)

users/models.py
from django.db import models
from django.contrib.auth.models import User
from locationlib.models import Location

# Create your models here.
class Profile(models.Model):
	user = models.ForeignKey(User, unique=True)
	firstName = models.CharField(max_length=50, blank=True, verbose_name="First Name")
	lastName = models.CharField(max_length=50, blank=True, verbose_name="Last Name")
	about = models.CharField(max_length=500, blank=True, verbose_name="About")

	def __unicode__(self):
		profileName = self.user.username + "_profile"
		return profileName

	def get_locations(self):
		# returns list of all locations related to user
		return Location.objects.filter(user=self.user)

	

users/forms.py
from django.forms import ModelForm
from users.models import Profile

class ProfileForm(ModelForm):
	class Meta:
		model = Profile
		fields = ['firstName','lastName','about','user']

users/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from locationlib.models import Location
from users.models import Profile
from users.forms import ProfileForm

def verifyUser(request, requestedUser): # helper function
	# checks whether the remote user matches the user_id in url
	currentUser = request.user
	return currentUser == requestedUser

def profile(request, user_id): # page
	# displays info about particular user
	user = get_object_or_404(User, pk=user_id)
	userProfile = Profile.objects.get(user=user) 
	context = {
		'user':user,
		'profile':userProfile,
		'request':request,
		'recent_location_list': userProfile.get_locations()[:5],
		'loggedin':user.is_authenticated(),
	}
	return render(request, 'users/profile.html', context) 

def edit(request, user_id): # page
	# displays form to edit profile
	user = get_object_or_404(User, pk=user_id)
	verifyUser(request, user)
	userProfile = Profile.objects.get(user=user)
	form = ProfileForm()
	context = {
		'profile':userProfile, 
		'user':user, 
		'form':form,
		'request':request,
	}
	return render(request, 'users/edit.html', context)

def save(request, user_id): # action
	# saves changes to user profile
	user = get_object_or_404(User, pk=user_id)
	userProfile = Profile.objects.get(user=user)
	if request.method == 'POST':
		form = ProfileForm(request.POST,instance=userProfile)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse('users:profile', args=[user_id]))
		else:
			
			return HttpResponseRedirect(reverse('users:edit', args=[user_id]))

def places_index(request,user_id):
	user = get_object_or_404(User, pk=user_id)
	userProfile = Profile.objects.get(user=user)
	location_list = userProfile.get_locations()
	context = {
		'user':user,
		'profile':userProfile,
		'location_list':location_list,
		'request':request,
		'loggedin': user.is_authenticated(),
	}
	return render(request, 'users/index.html', context)

def add(request, user_id):
	user = get_object_or_404(User, pk=user_id)
	return HttpResponseRedirect(reverse('locationlib:new'))
	

users/templates/users/edit.html
<head>
	<title>pushpin'd | Edit Profile</title>
	<meta name='description' content='displays form for editing profile information' />

	{% load staticfiles %}
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
	<script src='{% static "locationlib/bootstrap.js" %}'></script>
	<link rel="stylesheet" type='text/css' href="{% static 'users/style.css' %}" />
	<link rel="stylesheet" type='text/css' href="{% static 'locationlib/bootstrap.min.css' %}" />
</head>

<body>
	<!-- Header -->
	<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
	    <div class="container">
	        <div class="navbar-header">
	            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
	            <span class="sr-only">Toggle navigation</span>
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	            </button>
	            <a class="navbar-brand" href="/">pushpin'd</a>
	        </div>
	        <div class="navbar-collapse collapse">
		        <ul class="nav navbar-nav">
		            <li><a href="{% url 'home' %}">Home</a></li>
		            <li><a href="#about">About</a></li>
		            <li><a href="#contact">Contact</a></li>
	            	<li class="dropdown active">
	            		<a href='#' class="dropdown-toggle" data-toggle="dropdown">You <span class="caret"></span></a>
		            	<ul class="dropdown-menu" role="menu">
			                <li><a href='{% url "users:profile" request.user.id %}'>Profile</a></li>
			                <li><a href="{% url 'users:places' request.user.id %}">Your Places</a></li>
			                <li><a href="{% url 'users:add' request.user.id %}">New Place</a></li>
			                <li><a href="{% url 'users:edit' request.user.id  %}">Edit Profile</a></li>
			            </ul>
			        </li>    
		        </ul>
            	<ul class="nav navbar-nav navbar-right">
		    		<li><a href='{% url "logout" %}' >Log out</a></li>
		    	</ul>
		    </div><!--/.navbar-collapse -->
	    </div>
	</div>

	<!-- Profile edit form -->
	<div class="container" id="profile-edit-form">
		<h2><b><span class='glyphicon glyphicon-pencil'></span> Edit your profile.</b></h2>
		<form action='{% url "users:save" user.id %}' method = "post">
			{% csrf_token %}
			<label for="id_firstName">First Name:</label><br> 
			<input id="id_firstName" maxlength="50" name="firstName" type="text" value='{{profile.firstName}}' class='form-control' /><br>
			<label for="id_lastName">Last Name:</label><br>
			<input id="id_lastName" maxlength="50" name="lastName" type="text" value='{{profile.lastName}}' class="form-control" /><br>
			<label for="id_about">About:</label> <br>
			<textarea id="id_about" maxlength="500" name="about" type="text" class="form-control">{{profile.about}}</textarea><br>
			<select id="id_user" name="user" style='display:none'>
			<option value="{{user.id}}" selected="selected">{{user}}</option>
			</select>
			<input type='submit' value="Save Changes" class="btn btn-lg btn-primary btn-block">
		</form>
	</div>
</body>

users/templates/users/index.html
<head>
	<title>{{user}} | Places</title>
	<meta name='description' content='displays a list of locations saved by user' />

	{% load staticfiles %}
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
	<script src='{% static "locationlib/bootstrap.min.js" %}'></script>
	<script type="text/javascript"
      		src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA7Lch5ls1gG_axoxz9elNrJAvxXlM2abc">
    	</script>
	<script>
		var map;
		var markers = [];
		var infoWindows = [];

		var location_list = [];
		
		function initialize() {
			// specify map init vars
			var center = new google.maps.LatLng(parseFloat('{{location_list.0.latitude}}'),parseFloat('{{location_list.0.longitude}}'));

			console.log('var center set: ({{location_list.0.longitude}},{{location_list.0.latitude}})');

			mapOptions = {
				zoom:12,
				center:center
			};

			var map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);

			console.log('var map set');
			
			// load location markers + location object for all locations

			{% for location in location_list %}
				position = new google.maps.LatLng(parseFloat('{{location.latitude}}'),parseFloat('{{location.longitude}}'));
				name = "{{location.name}}";
				addMarker(position,name);
			{% endfor %}

			setMapAll(map);

			console.log('location markers set');
		}

		function addMarker(position,name) {
			// adds a new marker and pushes it to the array
			var marker = new google.maps.Marker({
				position: position,
				map: map,
				title:name,
			});
			markers.push(marker);
		}

		function setMapAll(map) {
			// sets map/null for all markers
			for (var i=0; i < markers.length; i++) {
				markers[i].setMap(map);
			};
		}

		google.maps.event.addDomListener(window, 'load', initialize);
	</script>
	<link rel="stylesheet" type='text/css' href="{% static 'users/style.css' %}" />
	<link rel="stylesheet" type='text/css' href="{% static 'locationlib/bootstrap.min.css' %}" />
</head>

<body>
	<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
	    <div class="container">
	        <div class="navbar-header">
	            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
	            <span class="sr-only">Toggle navigation</span>
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	            </button>
	            <a class="navbar-brand" href="/">pushpin'd</a>
	        </div>
	        <div class="navbar-collapse collapse">
		        <ul class="nav navbar-nav">
		            <li><a href="{% url 'home' %}">Home</a></li>
		            <li><a href="#about">About</a></li>
		            <li><a href="#contact">Contact</a></li>
		            {% if loggedin %}
		            	<li class="dropdown active">
		            		<a href='#' class="dropdown-toggle" data-toggle="dropdown">You <span class="caret"></span></a>
			            	<ul class="dropdown-menu" role="menu">
				                <li><a href='{% url "users:profile" request.user.id %}'>Profile</a></li>
				                <li><a href="{% url 'users:places' request.user.id %}">Your Places</a></li>
				                <li><a href="{% url 'users:add' request.user.id %}">New Place</a></li>
				                <li><a href="{% url 'users:edit' request.user.id  %}">Edit Profile</a></li>
				            </ul>
				        </li>
		            {% endif %}
		        </ul>
	        	{% if not loggedin %}
		        	<form class="navbar-form navbar-right" role="form" action="{% url 'authenticator' %}" method="POST">
			            <div id="mini-login" class="form-group">
							{% csrf_token %}
							<input type='text' placeholder="Username" name="username" class="form-control">
							<input type='password' placeholder="Password" name="password" class="form-control">
							<input type='Submit' value='Log In' class="btn btn-success">
						</div>
		            </form>
	            {% else %}
	            	<ul class="nav navbar-nav navbar-right">
			    		<li><a href='{% url "logout" %}' >Log out</a></li>
			    	</ul>
			    {% endif %}
		    </div><!--/.navbar-collapse -->
	    </div>
	</div>

	<div class="container" id='location-sidebar'>
		<div id="location-list-header">
			<br>
			<h4>   
			{% if user.id != request.user.id %}
				{% if profile.firstName != '' %}
				<a href='{% url "users:profile" user.id %}'>{{ profile.firstName}}'s</a> Saved Places
				{% else %}
				<a href='{% url "users:profile" user.id %}'>{{user}}'s</a> Saved Places
				{% endif %}
			{% else %}
				<a href="{% url 'users:profile' user.id %}">Your</a> Saved Places
			{% endif %}
			</h4>
		</div>

		<div class="container" id="location-list">
			<div class="list-group">
				{% if location_list %}
					{% for location in location_list %}
						<a class="list-group-item" href="{% url 'locationlib:detail' location.id %}">
							<div class="location-container" id="{{location.id}}">
								<h4 class="list-group-item-header">{{location.name}}</h4></li>
								<p class="list-group-item-text">{{location.custDescription}}</p>
							</div>
						</a>
					{% endfor %}
					{% if user == request.user %}
						<a class="list-group-item" href="{% url 'users:add' user.id %}">
							<div class="container">
								<h4 class="list-group-item-text"><span class="glyphicon glyphicon-plus"></span> Add New Place?</h4><br>
							</div>
						</a>
					{% endif %}
					</ul>
				{% else %}
					<p>no places saved! :(</p>
					{% if user == request.user %}
					<a href="{% url 'users:add' user.id %}">add a new place?</a>
					{% endif %}
				{% endif %}
			</div>
		</div>
	</div>

	<div id="map-canvas"></div>
</body>

users/templates/users/profile.html
<head>
	<title>pushpin'd | {{user}}</title>
	<meta name='description' content="displays a particular user's profile" />

	{% load staticfiles %}
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
	<script src='{% static "locationlib/bootstrap.min.js" %}'></script>
	<link rel="stylesheet" type='text/css' href="{% static 'users/style.css' %}" />
	<link rel="stylesheet" type='text/css' href="{% static 'locationlib/bootstrap.min.css' %}" />
</head>

<body>
	<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
	    <div class="container">
	        <div class="navbar-header">
	            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
	            <span class="sr-only">Toggle navigation</span>
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	            </button>
	            <a class="navbar-brand" href="/">pushpin'd</a>
	        </div>
	        <div class="navbar-collapse collapse">
		        <ul class="nav navbar-nav">
		            <li><a href="{% url 'home' %}">Home</a></li>
		            <li><a href="#about">About</a></li>
		            <li><a href="#contact">Contact</a></li>
		            {% if loggedin %}
		            	<li class="dropdown active">
		            		<a class="dropdown-toggle" data-toggle="dropdown">You <span class="caret"></span></a>
			            	<ul class="dropdown-menu" role="menu">
				                <li><a href='{% url "users:profile" request.user.id %}'>Profile</a></li>
				                <li><a href="{% url 'users:places' request.user.id %}">Your Places</a></li>
				                <li><a href="{% url 'users:add' request.user.id %}">New Place</a></li>
				                <li><a href="{% url 'users:edit' request.user.id  %}">Edit Profile</a></li>
				            </ul>
				        </li>
		            {% endif %}
		        </ul>
	        	{% if not loggedin %}
		        	<form class="navbar-form navbar-right" role="form" action="{% url 'authenticator' %}" method="POST">
			            <div id="mini-login" class="form-group">
							{% csrf_token %}
							<input type='text' placeholder="Username" name="username" class="form-control">
							<input type='password' placeholder="Password" name="password" class="form-control">
							<input type='Submit' value='Log In' class="btn btn-success">
						</div>
		            </form>
	            {% else %}
	            	<ul class="nav navbar-nav navbar-right">
			    		<li><a href='{% url "logout" %}' >Log out</a></li>
			    	</ul>
			    {% endif %}
		    </div><!--/.navbar-collapse -->
	    </div>
	</div>


	<!-- PROFILE INFO -->
	<div class='cover-container' id='profile-cover'>
		<p>placeholder for cover photo</p>
	<div>

	<div class='container' id='profile-basic-info'>
		<div class=''>
			{% if profile.firstName != '' %}
				<div class='container' id='profile-name'>
					<p>{{profile.firstName}} {{profile.lastName}}</p>
				</div>
			{% endif %}
			<div class='container' id='profile-username'>
				<p>{{profile.user.username}}</p>
			</div>
		</div>
	</div>

	<div class="container" id="profile-about">
		<p>{{profile.about}}</p>
	</div>

	{% if user == request.user %}
		<div class='container' id='profile-edit-link'>
			<div class=''>
				<a href="{% url 'users:edit' request.user.id %}"><span class='glyphicon glyphicon-pencil'></span> edit profile</a>
			</div>
		</div>
	{% endif %}

	{% if recent_location_list|length != 0 %}
		<div class='container' id='profile-recent-locations'>
			<h4>{{profile.firstName}}'s Recent Places</h4>
			<div class='list-group'>
				{% for location in recent_location_list %}
					<a class="list-group-item" href="{% url 'locationlib:detail' location.id %}">
						<div class="container" id="item-container">
							<h4 class="list-group-item-header">{{location.name}}</h4></li>
							<p class="list-group-item-text">{{location.custDescription}}</p>
						</div>
					</a>
				{% endfor %}
			</div>
		</div>

	<div class='container' id="profile-more-locations">
		<div class="well well-sm">
			<a href="{% url 'users:places' user.id %}">See all their saved places!</a>
		</div>
	</div>

	{% else %}
		<div class='container' id='profile-no-locations'>
			<div class=''>
				<a href="{% url 'users:add' request.user.id %}">Add your first place?</a>
			</div>
		</div>
	{% endif %}

</body>