pushpin/urls.py
from django.conf.urls import patterns,include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'pushpin.views.home', name='home'),
    url(r'^signup/$', 'pushpin.views.signup', name="signup"),
    url(r'^login/$', 'pushpin.views.userLogin', name="userLogin"),
    url(r'^newuser/$', 'pushpin.views.createUser', name='createUser'),
    url(r'^authenticator/$', 'pushpin.views.authenticator', name='authenticator'),
    url(r'^logout/$', 'pushpin.views.userLogout', name='logout'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^locationlib/', include('locationlib.urls', namespace="locationlib")),
    url(r'^users/', include('users.urls', namespace='users')),
    )

users/urls.py
from django.conf.urls import patterns, url

from users import views

urlpatterns = patterns('',
	url(r'^(?P<user_id>\d+)/$' , views.profile, name='profile'),
	url(r'^(?P<user_id>\d+)/edit/$', views.edit, name='edit'),
	url(r'^(?P<user_id>\d+)/save/$', views.save, name='save'),
	url(r'^(?P<user_id>\d+)/places/$', views.places_index, name='places'),
	url(r'^(?P<user_id>\d+)/add/$', views.add, name='add'),
	)

locationlib/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
import datetime

class Location(models.Model):
	# name, longitude, latitude should not be changed
	name = models.CharField(max_length=70)
	longitude = models.DecimalField(max_digits=7,decimal_places=4)
	latitude = models.DecimalField(max_digits=7,decimal_places=4)

	# editable fields that the user can choose to use
	custDescription = models.CharField(max_length=500, default='')
	custName = models.CharField(max_length=70, default='')

	# each Location is linked to one user to allow custom names
	# note: this is not really efficient memory-wise?? bc
	# lots of users = lots of duplicate locations
	user = models.ForeignKey(User)
	saveDate = models.DateTimeField(default=timezone.now)

	def __unicode__(self):
		if self.custName != '':
			return self.custName
		else:
			return self.name

	def getCoordinates(self):
		if (type(self.longitude) != str) and (type(self.latitude) != str):
			return "(" + str(self.longitude)+ ", " + str(self.latitude) + ")"
		else:
			return None
	getCoordinates.admin_order_field = 'name'
	getCoordinates.short_description = 'Coordinates'

	def isRecent(self):
		now = timezone.now()
		return now - datetime.timedelta(hours=12) <= self.saveDate <= now

users/models.py
from django.db import models
from django.contrib.auth.models import User
from locationlib.models import Location

# Create your models here.
class Profile(models.Model):
	user = models.ForeignKey(User, unique=True)
	firstName = models.CharField(max_length=50, blank=True, verbose_name="First Name")
	lastName = models.CharField(max_length=50, blank=True, verbose_name="Last Name")
	about = models.CharField(max_length=500, blank=True, verbose_name="About")

	def __unicode__(self):
		profileName = self.user.username + "_profile"
		return profileName

	def get_locations(self):
		# returns list of all locations related to user
		return Location.objects.filter(user=self.user)

	

pushpin/forms.py
from django import forms
from django.contrib import auth
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class NewUserForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ['username', 'email']

	def save(self,commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data["email"]
		if commit:
			user.save()
		return user

templates/home.html
<head>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

	<title>pushpin'd | Home</title>

	<!-- jQuery, Bootstrap, Google API Key, and styling -->
	{% load staticfiles %}
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
	<script src='{% static "locationlib/bootstrap.min.js" %}'></script>
	<script type="text/javascript"
      		src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA7Lch5ls1gG_axoxz9elNrJAvxXlM2abc">
    	</script>
	<script>
		var map;
		var location;
		var service;
		var losangeles = new google.maps.LatLng(34.0576,-118.2508);
		var browserSupportFlag = new Boolean();
		var markers = [];

		function initialize() {
			// load map, load click listener
			mapOptions = {
				zoom:12,
			};

			var map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);

			// Try W3C Geolocation
			if (navigator.geolocation) {
				browserSupportFlag = True;
				navigator.geolocation.getCurrentPosition(function(position) {
					location = new google.maps.LatLng(position.coords.latitude,position.coords.longitude);
					map.setCenter(location);
					addMarker(location);
				}, function() {
					browserSupportFlag = false;
					handleNoGeolocation(browserSupportFlag);
				});
			}

			google.maps.event.addListener(map, 'click', loadClick(event));
			
		}

		function loadClick(event) {
			// clear map if needed
			if (markers != []) {
				setAllMap(null);
			}
			// create new marker
			addMarker(event.latLng);
			// render marker on map
			setAllMap(map);
			// update form
			var name = getName(event.latLng);
			var form = '
				{% csrf_token %}
				<p><input id="id_name" maxlength="70" name="name" type="text" value="'
				+ name +'" readonly /></p>
				<p><select id="id_user" name="user" style="display:none">
				<option value="{{request.user.id}}" selected="selected">{{request.user}}</option>
				</select></p>
				<p><input id="id_longitude" name="longitude" step="0.0001" type="number" value="'
				+ event.latLng.lng() + '" readonly /></p>
				<p><input id="id_latitude" name="latitude" step="0.0001" type="number" value="'
				+ event.latLng.lat() + '"/></p>
				<p><textarea id="id_custDescription" maxlength="500" name="custDescription" readonly />
					</textarea></p>
				<p><input type=submit value="Save this place!">
			';
			$("#autoadd").innerHTML(form);
		}


		function addMarker(position) {
			// adds a new marker and pushes it to the array
			var marker = new google.maps.Marker({
				position: position,
				map: map,
			});
			markers.push(marker);
		}

		function setMapAll(map) {
			// sets all markers to specified map (null/map)
			for (var i=0; i <= markers.length; i++) {
				markers[i].setMap(map);
				infoWindows[i].setMap(map);
			};
		}

		function getName(position) {
			// initiates a place search from given position
			var topName;
			var service = new google.maps.places.PlacesService(map);
			var request = {
				location:position,
				radius:100,
				type: [
					amusement_park,aquarium,art_gallery,bakery,bar,beauty_salon,
					book_store,bowling_alley,bus_station,cafe,campground,casino,
					cemetery,city_hall,clothing_store,convenience_store,
					department_store,museum,night_club,park,parking,pet_store,
					restaurant,rv_park,school,shoe_store,shopping_mall,spa,
					stadium,store,subway_station,train_station,university,zoo,
					establishment,florist,food,gas_station,jewelery_store,library,
					lodging,movie_theater
				]
			};
			service.radarSearch(request,function(results, status){
				// radar search callback
				if (status === google.maps.places.PlacesServiceStatus.OK) {
				    var topName = results[0].name;
				} else if (status === google.maps.places.PlacesServiceStatus.ZERO_RESULTS) {
					var topName = "Unknown";
				} else {
					alert(status);
					return;
				}
			});
			return topName;
		}

		function handleNoGeolocation(errorFlag) {
				// display error alert about geolocation service and
				// sets default location to LA
				if (errorFlag === true) {
					alert("Geolocation service failed.");
				} else {
					alert("Your browser doesn't support geolocation.");
				}
				location = losangeles;
				map.setCenter(location);
			}

		google.maps.event.addDomListener(window, 'load', initialize);
	</script>
	<link rel="stylesheet" type='text/css' href="{% static 'style.css' %}" />
	<link rel="stylesheet" type='text/css' href="{% static 'locationlib/bootstrap.min.css' %}" />
</head>

<body class="home">
	<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
	    <div class="container">
	        <div class="navbar-header">
	            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
	            <span class="sr-only">Toggle navigation</span>
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	            </button>
	            <a class="navbar-brand" href="/">pushpin'd</a>
	        </div>
	        <div class="navbar-collapse collapse">
		        <ul class="nav navbar-nav">
		            <li class="active"><a href="{% url 'home' %}">Home</a></li>
		            <li><a href="#about">About</a></li>
		            <li><a href="#contact">Contact</a></li>
		            {% if loggedin %}
		            	<li class="dropdown">
		            		<a href='#' class="dropdown-toggle" data-toggle="dropdown">You <span class="caret"></span></a>
			            	<ul class="dropdown-menu" role="menu">
				                <li><a href='{% url "users:profile" request.user.id %}'>Profile</a></li>
				                <li><a href="{% url 'users:places' request.user.id %}">Your Places</a></li>
				                <li><a href="{% url 'users:add' request.user.id %}">New Place</a></li>
				                <li><a href="{% url 'users:edit' request.user.id  %}">Edit Profile</a></li>
				            </ul>
				        </li>
		            {% endif %}
		        </ul>
	        	{% if not loggedin %}
		        	<form class="navbar-form navbar-right" role="form" action="{% url 'authenticator' %}" method="POST">
			            <div id="mini-login" class="form-group">
							{% csrf_token %}
							<input type='text' placeholder="Username" name="username" class="form-control">
							<input type='password' placeholder="Password" name="password" class="form-control">
							<input type='Submit' value='Log In' class="btn btn-success">
						</div>
		            </form>
	            {% else %}
	            	<ul class="nav navbar-nav navbar-right">
			    		<li><a href='{% url "logout" %}' >Log out</a></li>
			    	</ul>
			    {% endif %}
		    </div><!--/.navbar-collapse -->
	    </div>
	</div>
	
	<!-- Sign up Jumbotron -->
	{% if not loggedin %}
	<div class="jumbotron">O
      <div class="container" id="home-jumbotron">
        <h1>Welcome to pushpin'd!</h1>
        <p>Looking for a better way to remember all the best places to eat, play, hang out, or just take in the view? What if you could do that and more with just a click of a button. When you start using pushpin'd, it's easy to save, organize, and share all your favorite spots, anywhere in the world! Let pushpin'd do the work for you, so you can stop wondering where to go and start having more fun!</p>
        <p><a class="btn btn-primary btn-lg" role="button" href='{% url "signup" %}'>Sign up! &raquo;</a></p>
      </div>
    </div>

    <!-- Explore locations (alt. display for logged in users) -->
    {% else %}
    <div id='map-canvas'></div>
    <div id='autoadd-form'>
    	<form id='autoadd' action='.' method="post">
    	</form>
    </div>
    {% endif %}

</body>

templates/login.html
<head>
	<title>Pushpin'd | Login</title>

	<!-- jQuery, Bootstrap, and styling -->
	{% load staticfiles %}
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
	<script src='{% static "locationlib/bootstrap.js" %}'></script>
	<link rel="stylesheet" type='text/css' href="{% static 'locationlib/bootstrap.min.css' %}" />
	<link rel="stylesheet" type='text/css' href="{% static 'style.css' %}" />
</head>

<body id="body-login">
	<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
	    <div class="container">
	        <div class="navbar-header">
	            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
	            <span class="sr-only">Toggle navigation</span>
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	            </button>
	            <a class="navbar-brand" href="/">pushpin'd</a>
	        </div>
	    </div>
	</div>

    <div class="container">

      <form class="form-signin" role="form" action="{% url 'authenticator' %}" method="POST">
        <h2 class="form-signin-heading">Welcome back!</h2>
        {% csrf_token %}
        <input type="username" class="form-control" placeholder="Username" name="username" required autofocus>
        <input type="password" class="form-control" placeholder="Password" name="password" required>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Log in</button>
      </form>

    </div> <!-- /container -->

    <div id="signup-login-swap">
		<p>Not a user? <a href='{% url "signup" %}'>Sign up here!</a></p>
	</div>
</body>

templates/signup.html
<head>
	<title>Pushpin'd | Sign Up!</title>

	<!-- jQuery, Bootstrap, and styling -->
	{% load staticfiles %}
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
	<script src='{% static "locationlib/bootstrap.js" %}'></script>
	<link rel="stylesheet" type='text/css' href="{% static 'style.css' %}" />
	<link rel="stylesheet" type='text/css' href="{% static 'locationlib/bootstrap.min.css' %}" />
</head>

<body id="body-signup">
	<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
	    <div class="container">
	        <div class="navbar-header">
	            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
	            <span class="sr-only">Toggle navigation</span>
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	            </button>
	            <a class="navbar-brand" href="{% url 'home' %}">pushpin'd</a>
	        </div>
	    </div>
	</div>

	<div class="container">
		<form action='{% url "createUser" %}' method="POST" class='form-signin' role='form'>
			<h2 class="form-signin-heading">Sign up for pushpin'd!</h2>
			{% csrf_token %}
			<label for="id_username" type="text">Username:</label>
				<input id="id_username" type="text" name="username" class="form-control" required autofocus>
			<label for="id_email" type="text">Email:</label>
				<input id="id_email" type="email" name="email" class="form-control" required>
			<label for="id_password1" type="text">Password:</label>
				<input id="id_password1" type="password" name="password1" class="form-control" required>
			<label for="id_password2" type='text'>Confirm Password:</label>
				<input id="id_password2" type="password" name='password2' class='form-control' required>
			<input type="submit" value="Sign up!" class="btn btn-lg btn-primary btn-block"> 
		</form>
	<div>

	<div id="signup-login-swap">
		<p>Already a user? <a href='{% url "userLogin" %}'>Log in here!</a></p>
	</div>
</body>