locationlib/urls.py
from django.conf.urls import patterns, url

from locationlib import views

urlpatterns = patterns('',
	url(r'^$', views.index, name='index'),
	url(r'^new/$', views.new, name='new'),
	url(r'^savenew/$', views.savenew, name='savenew'),
	url(r'^(?P<location_id>\d+)/$', views.detail, name='detail'),
	url(r'^(?P<location_id>\d+)/edit/$', views.edit, name='edit'),
	url(r'^(?P<location_id>\d+)/save/$', views.save, name='save'),
	url(r'^(?P<location_id>\d+)/delete/$', views.delete, name='delete'),
	)

pushpin/urls.py
from django.conf.urls import patterns,include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'pushpin.views.home', name='home'),
    url(r'^signup/$', 'pushpin.views.signup', name="signup"),
    url(r'^login/$', 'pushpin.views.userLogin', name="userLogin"),
    url(r'^newuser/$', 'pushpin.views.createUser', name='createUser'),
    url(r'^authenticator/$', 'pushpin.views.authenticator', name='authenticator'),
    url(r'^logout/$', 'pushpin.views.userLogout', name='logout'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^locationlib/', include('locationlib.urls', namespace="locationlib")),
    url(r'^users/', include('users.urls', namespace='users')),
    )

users/urls.py
from django.conf.urls import patterns, url

from users import views

urlpatterns = patterns('',
	url(r'^(?P<user_id>\d+)/$' , views.profile, name='profile'),
	url(r'^(?P<user_id>\d+)/edit/$', views.edit, name='edit'),
	url(r'^(?P<user_id>\d+)/save/$', views.save, name='save'),
	url(r'^(?P<user_id>\d+)/places/$', views.places_index, name='places'),
	url(r'^(?P<user_id>\d+)/add/$', views.add, name='add'),
	)

locationlib/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
import datetime

class Location(models.Model):
	# name, longitude, latitude should not be changed
	name = models.CharField(max_length=70)
	longitude = models.DecimalField(max_digits=7,decimal_places=4)
	latitude = models.DecimalField(max_digits=7,decimal_places=4)

	# editable fields that the user can choose to use
	custDescription = models.CharField(max_length=500, default='')
	custName = models.CharField(max_length=70, default='')

	# each Location is linked to one user to allow custom names
	# note: this is not really efficient memory-wise?? bc
	# lots of users = lots of duplicate locations
	user = models.ForeignKey(User)
	saveDate = models.DateTimeField(default=timezone.now)

	def __unicode__(self):
		if self.custName != '':
			return self.custName
		else:
			return self.name

	def getCoordinates(self):
		if (type(self.longitude) != str) and (type(self.latitude) != str):
			return "(" + str(self.longitude)+ ", " + str(self.latitude) + ")"
		else:
			return None
	getCoordinates.admin_order_field = 'name'
	getCoordinates.short_description = 'Coordinates'

	def isRecent(self):
		now = timezone.now()
		return now - datetime.timedelta(hours=12) <= self.saveDate <= now

locationlib/forms.py
from django.forms import ModelForm
from locationlib.models import Location

class LocationForm(ModelForm):
	class Meta:
		model = Location
		fields = ['name', 'user','longitude','latitude','custDescription']

locationlib/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.utils import timezone
from locationlib.models import Location
from locationlib.forms import LocationForm

def index(request):
	# lists recent saved locations
	location_list = Location.objects.filter(
		saveDate__lte=timezone.now
	).order_by('-saveDate')[:5]
	context = {'location_list': location_list}
	return render(request, 'locationlib/index.html', context)

def new(request):
	form = LocationForm().as_p()
	context = {
		"form":form,
		"request":request,
	}
	return render(request, 'locationlib/new.html', context)
	
def detail(request, location_id):
	# displays info about particular location
	location = get_object_or_404(Location, pk=location_id)
	context = {
		'location':location,
		'user':location.user,
		'request':request,
	}
	return render(request, 'locationlib/detail.html', context)

def edit(request,location_id):
	# displays information edit form
	location = get_object_or_404(Location, pk=location_id)
	context = {
		'location':location,
		'request':request
	}
	return render(request, 'locationlib/edit.html', context)

def save(request, location_id):
	# saves changes from edit form
	l = get_object_or_404(Location, pk=location_id)
	# uses TRY/EXCEPT method.. switch to form.is_valid() later
	try:
		l.custName = request.POST['name']
		l.custDescription = request.POST['description']
	except (AttributeError):
		return render(request, 'locationlib:detail.html', {
			'location': l,
			'error_message': "Input not valid.", # use more descriptive err msg?
			})
	else:
		l.save()
		return HttpResponseRedirect(reverse('locationlib:detail', args=(l.id,)))

def savenew(request):
	# saves a new location
	if request.method == 'POST':
		form = LocationForm(request.POST)
		if form.is_valid():
			newLocation = form.save()
			print "form valid"
			return HttpResponseRedirect(reverse('locationlib:detail', args=[newLocation.id]))
		print 'form reset'
		print 'form invalid'
		return render(request, 'locationlib/new.html', {'form': form, 'request':request})
	else:
		form = LocationForm()
		print 'form reset'
		print '**ERR:METHOD NOT POST**'
		return render(request, 'locationlib/new.html', {'form': form})

def delete(request, location_id):
	l = get_object_or_404(Location, pk=location_id)
	l.delete()
	return HttpResponseRedirect(reverse('users:places', args=[request.user.id]))

locationlib/templates/locationlib/detail.html
<html>
<head>
	<title>{{ location }} | Details</title>
	<meta name='description' content='displays detailed information about a particular location'/>

	<!-- jQuery, Bootstrap, and styling -->
	{% load staticfiles %}
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
	<script src='{% static "locationlib/bootstrap.min.js" %}'></script>
	<link rel="stylesheet" type='text/css' href="{% static 'locationlib/style.css'%}" />
	<link rel="stylesheet" type='text/css' href="{% static 'locationlib/bootstrap.min.css' %}" />
</head>

<body>
	<div id='page-header'>
		<h1>pushpin'd</h1>
		<a href='{% url "users:places" user.id %}'>back to places</a>
	</div>

	<div id='location-info'>
		<div id='location-info-header'>
		<h2>{{ location.name }}</h2>
		<h3>{{ location.custName }}</h3>
		</div>
		<div id='location-info-content'>
		<table>
			<tr>
				<td>Coordinates</td>
				<td>{{ location.getCoordinates }}</td>
			</tr>
			{% if location.custDescription != '' %}
			<tr>
				<td>About</td>
				<td>{{ location.custDescription }}</td>
			</tr>
			{% endif %}
		</table>
		</div>
		{% if request.user == location.user %}
		<a href="{% url 'locationlib:edit' location.id %}">edit info</a> 
		{% endif %}
	</div>
</body>
</html>

locationlib/templates/locationlib/edit.html
<head>
	<title>{{ location.name }} | Edit Info</title>
	<meta name='description' content='displays form for editing location information'/>
	<!-- jQuery, Bootstrap, and styling -->
	{% load staticfiles %}
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
	<script src='{% static "locationlib/bootstrap.min.js" %}'></script>
	<link rel="stylesheet" type='text/css' href="{% static 'locationlib/style.css'%}" />
	<link rel="stylesheet" type='text/css' href="{% static 'locationlib/bootstrap.min.css' %}" />
</head>

<body>
	<div id='page-header'>
		<h1><a href="{% url 'home' %}">Pushpin'd</h1>
		<a href="{% url 'users:places' request.user.id %}">back to places</a>
	</div>

	<div id="page-description">
		<p>Use this page to edit the name and description displayed for {{ location.name }}.</p>
	</div>

	<div id='edit-form'>
		<form action="{% url 'locationlib:save' location.id %}" method="post">
			{% csrf_token %}
			Name: <input type="text" name="name" value="{{ location.custName }}"><br>
			Description: <textarea name="description" rows="10" cols="40" maxlength='500'>{{ location.custDescription }}</textarea><br>
			<input type="submit" value="Save Changes">
		</form>
	</div>

	<div id='delete-button'>
		<form action="{% url 'locationlib:delete' location.id %}" method="post">
		{% csrf_token %}
		<input type='submit' value='Delete this place.'>
		</form>
	</div>
</body>

locationlib/templates/locationlib/index.html
<html>
<head>
	<title>Pushpin'd | Recent Places</title>
	<meta name='description' content='displays list of recently added locations'/>

	<!-- jQuery, Bootstrap, and styling -->
	{% load staticfiles %}
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
	<script src='{% static "locationlib/bootstrap.js" %}'></script>
	<link rel="stylesheet" type='text/css' href="{% static 'locationlib/style.css'%}" />
	<link rel="stylesheet" type='text/css' href="{% static 'locationlib/bootstrap.min.css' %}" />
</head>

<body>
	<div id='page-header'>
		<h1><a href="{% url 'home' %}">Pushpin'd</a></h1>
		<a href="{% url 'locationlib:new' %}">create new location</a>
	</div>
		
	<div id='recent-places'>
		<div id='recent-places-header'>
			<h2>Recently Saved Places</h2>
		</div>
		{% if location_list %}
			<ul>
			{% for location in location_list %}
				<li>
					<a href="{% url 'locationlib:detail' location.id %}">
					{% if location.custName == '' %}
						{{ location.name }}
					{% else %}
						{{ location.custName }} ({{ location.name }})
					{% endif %}
					</a>
				</li>
			{% endfor %}
			</ul>

		{% else %}
			<p>No places saved!</p>
		{% endif %}
	</div>
</body>
</html>

locationlib/templates/locationlib/new.html
<head>
	<title>Pushpin'd | New Place</title>
	<meta name="description" content="displays form for manually adding a new location" />

	<!-- jQuery, Bootstrap, and styling -->
	{% load staticfiles %}
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
	<script src='{% static "locationlib/bootstrap.min.js" %}'></script>
	<link rel="stylesheet" type='text/css' href="{% static 'locationlib/style.css'%}" />
	<link rel="stylesheet" type='text/css' href="{% static 'locationlib/bootstrap.min.css' %}" />
</head>

<body>
	<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
	    <div class="container">
	        <div class="navbar-header">
	            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
	            <span class="sr-only">Toggle navigation</span>
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	            </button>
	            <a class="navbar-brand" href="/">pushpin'd</a>
	        </div>
	        <div class="navbar-collapse collapse">
		        <ul class="nav navbar-nav">
		            <li><a href="{% url 'home' %}">Home</a></li>
		            <li><a href="#about">About</a></li>
		            <li><a href="#contact">Contact</a></li>
	            	<li class="dropdown active">
	            		<a href='#' class="dropdown-toggle" data-toggle="dropdown">You <span class="caret"></span></a>
		            	<ul class="dropdown-menu" role="menu">
			                <li><a href='{% url "users:profile" request.user.id %}'>Profile</a></li>
			                <li><a href="{% url 'users:places' request.user.id %}">Your Places</a></li>
			                <li><a href="{% url 'users:add' request.user.id %}">New Place</a></li>
			                <li><a href="{% url 'users:edit' request.user.id  %}">Edit Profile</a></li>
			            </ul>
			        </li>
		        </ul>
            	<ul class="nav navbar-nav navbar-right">
		    		<li><a href='{% url "logout" %}' >Log out</a></li>
		    	</ul>
		    </div><!--/.navbar-collapse -->
	    </div>
	</div>

	<div id='new-location-form'>
		<form action="{% url 'locationlib:savenew' %}" method="post">
			{% csrf_token %}
			<p><label for="id_name">Name:</label> <input id="id_name" maxlength="70" name="name" type="text" required autofocus/></p>
			<p><select id="id_user" name="user" style="display:none">
			<option value="{{request.user.id}}" selected="selected">{{request.user}}</option>
			</select></p>
			<p><label for="id_longitude">Longitude:</label> <input id="id_longitude" name="longitude" step="0.0001" type="number" required /></p>
			<p><label for="id_latitude">Latitude:</label> <input id="id_latitude" name="latitude" step="0.0001" type="number" required /></p>
			<p><label for="id_custDescription">Description:</label> <textarea id="id_custDescription" maxlength="500" name="custDescription" required/></textarea></p>

			<input type='submit' value='Save'>
		</form>
	</div>
</body>